Update .rancher-pipeline.yml file

diff --git a/.rancher-pipeline.yml b/.rancher-pipeline.yml
--- a/.rancher-pipeline.yml
+++ b/.rancher-pipeline.yml
@@ -4,32 +4,33 @@ stages:
   - runScriptConfig:
       image: maven:3.6.3-jdk-8
       shellScript: |-
-          LOG_TAG="CHIP-INFO"
-          MVN_SETTINGS_PATH="/root/.m2"
-          if [ -d "${MVN_SETTINGS_PATH}" ];then
-              mv ./settings.xml ${MVN_SETTINGS_PATH}
-              if [ $? -eq 0 ];then
-                 echo "[$LOG_TAG]Copy settings.xml to ${MVN_SETTINGS_PATH} success!"
-              else
-                 echo "[$LOG_TAG]Copy settings.xml to ${MVN_SETTINGS_PATH} fail!"
-              fi
-          else
-             mkdir -p ${MVN_SETTINGS_PATH} && mv ./settings.xml ${MVN_SETTINGS_PATH}
-             echo "[$LOG_TAG]Create path:${MVN_SETTINGS_PATH} and copy settings.xml to ${MVN_SETTINGS_PATH}!"
-          fi
-          echo "[$LOG_TAG]Current pwd:`pwd`"
-          ls -l
-          echo "[$LOG_TAG]===========Execute Maven CMD Build Project Start==========="
-          mvn clean package -Dmaven.test.skip=true
-          echo "[$LOG_TAG]===========Execute Maven CMD Build Project End==========="
-          echo "[$LOG_TAG]Dir:target ls -l:`pwd`"
-          ls -l ./target
+        LOG_TAG="CHIP-INFO"
+        MVN_SETTINGS_PATH="/root/.m2"
+        if [ -d "${MVN_SETTINGS_PATH}" ];then
+            mv ./settings.xml ${MVN_SETTINGS_PATH}
+            if [ $? -eq 0 ];then
+               echo "[$LOG_TAG]Copy settings.xml to ${MVN_SETTINGS_PATH} success!"
+            else
+               echo "[$LOG_TAG]Copy settings.xml to ${MVN_SETTINGS_PATH} fail!"
+            fi
+        else
+           mkdir -p ${MVN_SETTINGS_PATH} && mv ./settings.xml ${MVN_SETTINGS_PATH}
+           echo "[$LOG_TAG]Create path:${MVN_SETTINGS_PATH} and copy settings.xml to ${MVN_SETTINGS_PATH}!"
+        fi
+        echo "[$LOG_TAG]Current pwd:`pwd`"
+        ls -l
+        echo "[$LOG_TAG]===========Execute Maven CMD Build Project Start==========="
+        mvn clean package -Dmaven.test.skip=true
+        echo "[$LOG_TAG]===========Execute Maven CMD Build Project End==========="
+        echo "[$LOG_TAG]Dir:target ls -l:`pwd`"
+        ls -l ./target
 - name: Publish
   steps:
   - publishImageConfig:
       dockerfilePath: ./Dockerfile
       buildContext: .
-      tag: format:${CICD_EXECUTION_SEQUENCE}
+      tag: 127.0.0.1:34841/format:${CICD_EXECUTION_SEQUENCE}
+      registry: 127.0.0.1:34841
 - name: Deploy
   steps:
   - applyYamlConfig:
